//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSMCommunication.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSMCommunication.lang.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned number.
        /// </summary>
        public static string CMS_ERROR_1 {
            get {
                return ResourceManager.GetString("CMS_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call bared.
        /// </summary>
        public static string CMS_ERROR_10 {
            get {
                return ResourceManager.GetString("CMS_ERROR_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol error, unspecified.
        /// </summary>
        public static string CMS_ERROR_111 {
            get {
                return ResourceManager.GetString("CMS_ERROR_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internetworking , unspecified.
        /// </summary>
        public static string CMS_ERROR_127 {
            get {
                return ResourceManager.GetString("CMS_ERROR_127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telematic internetworking not supported.
        /// </summary>
        public static string CMS_ERROR_128 {
            get {
                return ResourceManager.GetString("CMS_ERROR_128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short message type 0 not supported.
        /// </summary>
        public static string CMS_ERROR_129 {
            get {
                return ResourceManager.GetString("CMS_ERROR_129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot replace short message.
        /// </summary>
        public static string CMS_ERROR_130 {
            get {
                return ResourceManager.GetString("CMS_ERROR_130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified TP-PID error.
        /// </summary>
        public static string CMS_ERROR_143 {
            get {
                return ResourceManager.GetString("CMS_ERROR_143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data code scheme not supported.
        /// </summary>
        public static string CMS_ERROR_144 {
            get {
                return ResourceManager.GetString("CMS_ERROR_144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message class not supported.
        /// </summary>
        public static string CMS_ERROR_145 {
            get {
                return ResourceManager.GetString("CMS_ERROR_145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified TP-DCS error.
        /// </summary>
        public static string CMS_ERROR_159 {
            get {
                return ResourceManager.GetString("CMS_ERROR_159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command cannot be actioned.
        /// </summary>
        public static string CMS_ERROR_160 {
            get {
                return ResourceManager.GetString("CMS_ERROR_160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command unsupported.
        /// </summary>
        public static string CMS_ERROR_161 {
            get {
                return ResourceManager.GetString("CMS_ERROR_161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified TP-Command error.
        /// </summary>
        public static string CMS_ERROR_175 {
            get {
                return ResourceManager.GetString("CMS_ERROR_175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPDU not supported.
        /// </summary>
        public static string CMS_ERROR_176 {
            get {
                return ResourceManager.GetString("CMS_ERROR_176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC busy.
        /// </summary>
        public static string CMS_ERROR_192 {
            get {
                return ResourceManager.GetString("CMS_ERROR_192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SC subscription.
        /// </summary>
        public static string CMS_ERROR_193 {
            get {
                return ResourceManager.GetString("CMS_ERROR_193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC System failure.
        /// </summary>
        public static string CMS_ERROR_194 {
            get {
                return ResourceManager.GetString("CMS_ERROR_194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SME address.
        /// </summary>
        public static string CMS_ERROR_195 {
            get {
                return ResourceManager.GetString("CMS_ERROR_195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination SME barred.
        /// </summary>
        public static string CMS_ERROR_196 {
            get {
                return ResourceManager.GetString("CMS_ERROR_196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SM Rejected-Duplicate SM.
        /// </summary>
        public static string CMS_ERROR_197 {
            get {
                return ResourceManager.GetString("CMS_ERROR_197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP-VPF not supported.
        /// </summary>
        public static string CMS_ERROR_198 {
            get {
                return ResourceManager.GetString("CMS_ERROR_198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP-VP not supported.
        /// </summary>
        public static string CMS_ERROR_199 {
            get {
                return ResourceManager.GetString("CMS_ERROR_199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D0 SIM SMS Storage full.
        /// </summary>
        public static string CMS_ERROR_208 {
            get {
                return ResourceManager.GetString("CMS_ERROR_208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SMS Storage capability in SIM.
        /// </summary>
        public static string CMS_ERROR_209 {
            get {
                return ResourceManager.GetString("CMS_ERROR_209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short message transfer rejected.
        /// </summary>
        public static string CMS_ERROR_21 {
            get {
                return ResourceManager.GetString("CMS_ERROR_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in MS.
        /// </summary>
        public static string CMS_ERROR_210 {
            get {
                return ResourceManager.GetString("CMS_ERROR_210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory capacity exceeded.
        /// </summary>
        public static string CMS_ERROR_211 {
            get {
                return ResourceManager.GetString("CMS_ERROR_211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim application toolkit busy.
        /// </summary>
        public static string CMS_ERROR_212 {
            get {
                return ResourceManager.GetString("CMS_ERROR_212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM data download error.
        /// </summary>
        public static string CMS_ERROR_213 {
            get {
                return ResourceManager.GetString("CMS_ERROR_213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified error cause.
        /// </summary>
        public static string CMS_ERROR_255 {
            get {
                return ResourceManager.GetString("CMS_ERROR_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination out of service.
        /// </summary>
        public static string CMS_ERROR_27 {
            get {
                return ResourceManager.GetString("CMS_ERROR_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unindentified subscriber.
        /// </summary>
        public static string CMS_ERROR_28 {
            get {
                return ResourceManager.GetString("CMS_ERROR_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility rejected.
        /// </summary>
        public static string CMS_ERROR_29 {
            get {
                return ResourceManager.GetString("CMS_ERROR_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown subscriber.
        /// </summary>
        public static string CMS_ERROR_30 {
            get {
                return ResourceManager.GetString("CMS_ERROR_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ME Failure.
        /// </summary>
        public static string CMS_ERROR_300 {
            get {
                return ResourceManager.GetString("CMS_ERROR_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS service of ME reserved.
        /// </summary>
        public static string CMS_ERROR_301 {
            get {
                return ResourceManager.GetString("CMS_ERROR_301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not allowed.
        /// </summary>
        public static string CMS_ERROR_302 {
            get {
                return ResourceManager.GetString("CMS_ERROR_302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not supported.
        /// </summary>
        public static string CMS_ERROR_303 {
            get {
                return ResourceManager.GetString("CMS_ERROR_303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PDU mode parameter.
        /// </summary>
        public static string CMS_ERROR_304 {
            get {
                return ResourceManager.GetString("CMS_ERROR_304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Text mode parameter.
        /// </summary>
        public static string CMS_ERROR_305 {
            get {
                return ResourceManager.GetString("CMS_ERROR_305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM not inserted.
        /// </summary>
        public static string CMS_ERROR_310 {
            get {
                return ResourceManager.GetString("CMS_ERROR_310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM PIN required.
        /// </summary>
        public static string CMS_ERROR_311 {
            get {
                return ResourceManager.GetString("CMS_ERROR_311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PH-SIM PIN required.
        /// </summary>
        public static string CMS_ERROR_312 {
            get {
                return ResourceManager.GetString("CMS_ERROR_312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM failure.
        /// </summary>
        public static string CMS_ERROR_313 {
            get {
                return ResourceManager.GetString("CMS_ERROR_313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM busy.
        /// </summary>
        public static string CMS_ERROR_314 {
            get {
                return ResourceManager.GetString("CMS_ERROR_314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM wrong.
        /// </summary>
        public static string CMS_ERROR_315 {
            get {
                return ResourceManager.GetString("CMS_ERROR_315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM PUK required.
        /// </summary>
        public static string CMS_ERROR_316 {
            get {
                return ResourceManager.GetString("CMS_ERROR_316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM PIN2 required.
        /// </summary>
        public static string CMS_ERROR_317 {
            get {
                return ResourceManager.GetString("CMS_ERROR_317", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM PUK2 required.
        /// </summary>
        public static string CMS_ERROR_318 {
            get {
                return ResourceManager.GetString("CMS_ERROR_318", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory failure.
        /// </summary>
        public static string CMS_ERROR_320 {
            get {
                return ResourceManager.GetString("CMS_ERROR_320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid memory index.
        /// </summary>
        public static string CMS_ERROR_321 {
            get {
                return ResourceManager.GetString("CMS_ERROR_321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory full.
        /// </summary>
        public static string CMS_ERROR_322 {
            get {
                return ResourceManager.GetString("CMS_ERROR_322", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSC address unknown.
        /// </summary>
        public static string CMS_ERROR_330 {
            get {
                return ResourceManager.GetString("CMS_ERROR_330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network service.
        /// </summary>
        public static string CMS_ERROR_331 {
            get {
                return ResourceManager.GetString("CMS_ERROR_331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network timeout.
        /// </summary>
        public static string CMS_ERROR_332 {
            get {
                return ResourceManager.GetString("CMS_ERROR_332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No +CNMA expected.
        /// </summary>
        public static string CMS_ERROR_340 {
            get {
                return ResourceManager.GetString("CMS_ERROR_340", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network out of order.
        /// </summary>
        public static string CMS_ERROR_38 {
            get {
                return ResourceManager.GetString("CMS_ERROR_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary failure.
        /// </summary>
        public static string CMS_ERROR_41 {
            get {
                return ResourceManager.GetString("CMS_ERROR_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congestion.
        /// </summary>
        public static string CMS_ERROR_42 {
            get {
                return ResourceManager.GetString("CMS_ERROR_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recources unavailable.
        /// </summary>
        public static string CMS_ERROR_47 {
            get {
                return ResourceManager.GetString("CMS_ERROR_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested facility not subscribed.
        /// </summary>
        public static string CMS_ERROR_50 {
            get {
                return ResourceManager.GetString("CMS_ERROR_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error (The phone number you try to send your message to is invalid/ There is no network coverage or not enough money on a prepaid subscription/ The short message service center of the GSM network operator is temporarily out of service/ The GSM cell is overloaded).
        /// </summary>
        public static string CMS_ERROR_500 {
            get {
                return ResourceManager.GetString("CMS_ERROR_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User abort.
        /// </summary>
        public static string CMS_ERROR_512 {
            get {
                return ResourceManager.GetString("CMS_ERROR_512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to store.
        /// </summary>
        public static string CMS_ERROR_513 {
            get {
                return ResourceManager.GetString("CMS_ERROR_513", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Status.
        /// </summary>
        public static string CMS_ERROR_514 {
            get {
                return ResourceManager.GetString("CMS_ERROR_514", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device busy or Invalid Character in string.
        /// </summary>
        public static string CMS_ERROR_515 {
            get {
                return ResourceManager.GetString("CMS_ERROR_515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length.
        /// </summary>
        public static string CMS_ERROR_516 {
            get {
                return ResourceManager.GetString("CMS_ERROR_516", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in PDU.
        /// </summary>
        public static string CMS_ERROR_517 {
            get {
                return ResourceManager.GetString("CMS_ERROR_517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter.
        /// </summary>
        public static string CMS_ERROR_518 {
            get {
                return ResourceManager.GetString("CMS_ERROR_518", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length or character.
        /// </summary>
        public static string CMS_ERROR_519 {
            get {
                return ResourceManager.GetString("CMS_ERROR_519", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character in text.
        /// </summary>
        public static string CMS_ERROR_520 {
            get {
                return ResourceManager.GetString("CMS_ERROR_520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer expired.
        /// </summary>
        public static string CMS_ERROR_521 {
            get {
                return ResourceManager.GetString("CMS_ERROR_521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation temporary not allowed.
        /// </summary>
        public static string CMS_ERROR_522 {
            get {
                return ResourceManager.GetString("CMS_ERROR_522", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM not ready.
        /// </summary>
        public static string CMS_ERROR_532 {
            get {
                return ResourceManager.GetString("CMS_ERROR_532", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Broadcast error unknown.
        /// </summary>
        public static string CMS_ERROR_534 {
            get {
                return ResourceManager.GetString("CMS_ERROR_534", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol stack busy.
        /// </summary>
        public static string CMS_ERROR_535 {
            get {
                return ResourceManager.GetString("CMS_ERROR_535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter.
        /// </summary>
        public static string CMS_ERROR_538 {
            get {
                return ResourceManager.GetString("CMS_ERROR_538", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested facility not implemented.
        /// </summary>
        public static string CMS_ERROR_69 {
            get {
                return ResourceManager.GetString("CMS_ERROR_69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator determined barring.
        /// </summary>
        public static string CMS_ERROR_8 {
            get {
                return ResourceManager.GetString("CMS_ERROR_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid short message transfer reference value.
        /// </summary>
        public static string CMS_ERROR_81 {
            get {
                return ResourceManager.GetString("CMS_ERROR_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message unspecified.
        /// </summary>
        public static string CMS_ERROR_95 {
            get {
                return ResourceManager.GetString("CMS_ERROR_95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mandatory information.
        /// </summary>
        public static string CMS_ERROR_96 {
            get {
                return ResourceManager.GetString("CMS_ERROR_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type non existent or not implemented.
        /// </summary>
        public static string CMS_ERROR_97 {
            get {
                return ResourceManager.GetString("CMS_ERROR_97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message not compatible with short message protocol.
        /// </summary>
        public static string CMS_ERROR_98 {
            get {
                return ResourceManager.GetString("CMS_ERROR_98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information element non-existent or not implemente.
        /// </summary>
        public static string CMS_ERROR_99 {
            get {
                return ResourceManager.GetString("CMS_ERROR_99", resourceCulture);
            }
        }
    }
}
