//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSMCommunication.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class id_ID {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal id_ID() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSMCommunication.lang.id-ID", typeof(id_ID).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomor tidak ditugaskan.
        /// </summary>
        internal static string CMS_ERROR_1 {
            get {
                return ResourceManager.GetString("CMS_ERROR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panggilan dilarang.
        /// </summary>
        internal static string CMS_ERROR_10 {
            get {
                return ResourceManager.GetString("CMS_ERROR_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protokol error, tidak ditentukan.
        /// </summary>
        internal static string CMS_ERROR_111 {
            get {
                return ResourceManager.GetString("CMS_ERROR_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internetworking, tidak ditentukan.
        /// </summary>
        internal static string CMS_ERROR_127 {
            get {
                return ResourceManager.GetString("CMS_ERROR_127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telematika internetworking tidak didukung.
        /// </summary>
        internal static string CMS_ERROR_128 {
            get {
                return ResourceManager.GetString("CMS_ERROR_128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesan singkat tipe 0 tidak didukung.
        /// </summary>
        internal static string CMS_ERROR_129 {
            get {
                return ResourceManager.GetString("CMS_ERROR_129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak dapat menggantikan pesan singkat.
        /// </summary>
        internal static string CMS_ERROR_130 {
            get {
                return ResourceManager.GetString("CMS_ERROR_130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak disebutkan TP-PID error.
        /// </summary>
        internal static string CMS_ERROR_143 {
            get {
                return ResourceManager.GetString("CMS_ERROR_143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data skema kode tidak didukung.
        /// </summary>
        internal static string CMS_ERROR_144 {
            get {
                return ResourceManager.GetString("CMS_ERROR_144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelas pesan tidak didukung.
        /// </summary>
        internal static string CMS_ERROR_145 {
            get {
                return ResourceManager.GetString("CMS_ERROR_145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak disebutkan TP-DCS error.
        /// </summary>
        internal static string CMS_ERROR_159 {
            get {
                return ResourceManager.GetString("CMS_ERROR_159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command tidak dapat dikerjakan.
        /// </summary>
        internal static string CMS_ERROR_160 {
            get {
                return ResourceManager.GetString("CMS_ERROR_160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perintah tidak didukung.
        /// </summary>
        internal static string CMS_ERROR_161 {
            get {
                return ResourceManager.GetString("CMS_ERROR_161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak disebutkan TP-Command error.
        /// </summary>
        internal static string CMS_ERROR_175 {
            get {
                return ResourceManager.GetString("CMS_ERROR_175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPDU tidak didukung.
        /// </summary>
        internal static string CMS_ERROR_176 {
            get {
                return ResourceManager.GetString("CMS_ERROR_176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC sibuk.
        /// </summary>
        internal static string CMS_ERROR_192 {
            get {
                return ResourceManager.GetString("CMS_ERROR_192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak SC berlangganan.
        /// </summary>
        internal static string CMS_ERROR_193 {
            get {
                return ResourceManager.GetString("CMS_ERROR_193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC Sistem Kegagalan.
        /// </summary>
        internal static string CMS_ERROR_194 {
            get {
                return ResourceManager.GetString("CMS_ERROR_194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alamat SME salah.
        /// </summary>
        internal static string CMS_ERROR_195 {
            get {
                return ResourceManager.GetString("CMS_ERROR_195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tujuan SME ditolak.
        /// </summary>
        internal static string CMS_ERROR_196 {
            get {
                return ResourceManager.GetString("CMS_ERROR_196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SM Ditolak-Duplikat SM.
        /// </summary>
        internal static string CMS_ERROR_197 {
            get {
                return ResourceManager.GetString("CMS_ERROR_197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP-VPF tidak didukung.
        /// </summary>
        internal static string CMS_ERROR_198 {
            get {
                return ResourceManager.GetString("CMS_ERROR_198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP-VP tidak didukung.
        /// </summary>
        internal static string CMS_ERROR_199 {
            get {
                return ResourceManager.GetString("CMS_ERROR_199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penyimpanan D0 SIM SMS penuh.
        /// </summary>
        internal static string CMS_ERROR_208 {
            get {
                return ResourceManager.GetString("CMS_ERROR_208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak ada Penyimpanan SMS kemampuan dalam SIM.
        /// </summary>
        internal static string CMS_ERROR_209 {
            get {
                return ResourceManager.GetString("CMS_ERROR_209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer pesan singkat ditolak.
        /// </summary>
        internal static string CMS_ERROR_21 {
            get {
                return ResourceManager.GetString("CMS_ERROR_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terjadi Kerusakan di MS.
        /// </summary>
        internal static string CMS_ERROR_210 {
            get {
                return ResourceManager.GetString("CMS_ERROR_210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapasitas memori melebihi.
        /// </summary>
        internal static string CMS_ERROR_211 {
            get {
                return ResourceManager.GetString("CMS_ERROR_211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim aplikasi toolkit sibuk.
        /// </summary>
        internal static string CMS_ERROR_212 {
            get {
                return ResourceManager.GetString("CMS_ERROR_212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM download data error.
        /// </summary>
        internal static string CMS_ERROR_213 {
            get {
                return ResourceManager.GetString("CMS_ERROR_213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak disebutkan kesalahan penyebab.
        /// </summary>
        internal static string CMS_ERROR_255 {
            get {
                return ResourceManager.GetString("CMS_ERROR_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tujuan dari layanan sedang dalam perbaikan.
        /// </summary>
        internal static string CMS_ERROR_27 {
            get {
                return ResourceManager.GetString("CMS_ERROR_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unindentified pelanggan.
        /// </summary>
        internal static string CMS_ERROR_28 {
            get {
                return ResourceManager.GetString("CMS_ERROR_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fasilitas ditolak.
        /// </summary>
        internal static string CMS_ERROR_29 {
            get {
                return ResourceManager.GetString("CMS_ERROR_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak diketahui pelanggan.
        /// </summary>
        internal static string CMS_ERROR_30 {
            get {
                return ResourceManager.GetString("CMS_ERROR_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ME gagal.
        /// </summary>
        internal static string CMS_ERROR_300 {
            get {
                return ResourceManager.GetString("CMS_ERROR_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layanan SMS di ME dipesan.
        /// </summary>
        internal static string CMS_ERROR_301 {
            get {
                return ResourceManager.GetString("CMS_ERROR_301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operasi tidak diijinkan.
        /// </summary>
        internal static string CMS_ERROR_302 {
            get {
                return ResourceManager.GetString("CMS_ERROR_302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operasi tidak didukung.
        /// </summary>
        internal static string CMS_ERROR_303 {
            get {
                return ResourceManager.GetString("CMS_ERROR_303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDU mode parameter salah.
        /// </summary>
        internal static string CMS_ERROR_304 {
            get {
                return ResourceManager.GetString("CMS_ERROR_304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text mode parameter salah.
        /// </summary>
        internal static string CMS_ERROR_305 {
            get {
                return ResourceManager.GetString("CMS_ERROR_305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM not inserted.
        /// </summary>
        internal static string CMS_ERROR_310 {
            get {
                return ResourceManager.GetString("CMS_ERROR_310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM PIN diperlukan.
        /// </summary>
        internal static string CMS_ERROR_311 {
            get {
                return ResourceManager.GetString("CMS_ERROR_311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PH-SIM PIN diperlukan.
        /// </summary>
        internal static string CMS_ERROR_312 {
            get {
                return ResourceManager.GetString("CMS_ERROR_312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM gagal.
        /// </summary>
        internal static string CMS_ERROR_313 {
            get {
                return ResourceManager.GetString("CMS_ERROR_313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM sibuk.
        /// </summary>
        internal static string CMS_ERROR_314 {
            get {
                return ResourceManager.GetString("CMS_ERROR_314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM salah.
        /// </summary>
        internal static string CMS_ERROR_315 {
            get {
                return ResourceManager.GetString("CMS_ERROR_315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM PUK diperlukan.
        /// </summary>
        internal static string CMS_ERROR_316 {
            get {
                return ResourceManager.GetString("CMS_ERROR_316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM PIN2 diperlukan.
        /// </summary>
        internal static string CMS_ERROR_317 {
            get {
                return ResourceManager.GetString("CMS_ERROR_317", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM PUK2 diperlukan.
        /// </summary>
        internal static string CMS_ERROR_318 {
            get {
                return ResourceManager.GetString("CMS_ERROR_318", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory gagal.
        /// </summary>
        internal static string CMS_ERROR_320 {
            get {
                return ResourceManager.GetString("CMS_ERROR_320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory index salah.
        /// </summary>
        internal static string CMS_ERROR_321 {
            get {
                return ResourceManager.GetString("CMS_ERROR_321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory penuh.
        /// </summary>
        internal static string CMS_ERROR_322 {
            get {
                return ResourceManager.GetString("CMS_ERROR_322", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alamat SMSC tidak diketahui.
        /// </summary>
        internal static string CMS_ERROR_330 {
            get {
                return ResourceManager.GetString("CMS_ERROR_330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak ada Jaringan.
        /// </summary>
        internal static string CMS_ERROR_331 {
            get {
                return ResourceManager.GetString("CMS_ERROR_331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jaringan batas waktu .
        /// </summary>
        internal static string CMS_ERROR_332 {
            get {
                return ResourceManager.GetString("CMS_ERROR_332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak ada CNMA + diharapkan.
        /// </summary>
        internal static string CMS_ERROR_340 {
            get {
                return ResourceManager.GetString("CMS_ERROR_340", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaringan rusak.
        /// </summary>
        internal static string CMS_ERROR_38 {
            get {
                return ResourceManager.GetString("CMS_ERROR_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sementara gagal.
        /// </summary>
        internal static string CMS_ERROR_41 {
            get {
                return ResourceManager.GetString("CMS_ERROR_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macet.
        /// </summary>
        internal static string CMS_ERROR_42 {
            get {
                return ResourceManager.GetString("CMS_ERROR_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recources tidak tersedia.
        /// </summary>
        internal static string CMS_ERROR_47 {
            get {
                return ResourceManager.GetString("CMS_ERROR_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested facility not subscribed.
        /// </summary>
        internal static string CMS_ERROR_50 {
            get {
                return ResourceManager.GetString("CMS_ERROR_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fasilitas Diminta tidak berlangganan.
        /// </summary>
        internal static string CMS_ERROR_500 {
            get {
                return ResourceManager.GetString("CMS_ERROR_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pengguna membatalkan.
        /// </summary>
        internal static string CMS_ERROR_512 {
            get {
                return ResourceManager.GetString("CMS_ERROR_512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak dapat menyimpan.
        /// </summary>
        internal static string CMS_ERROR_513 {
            get {
                return ResourceManager.GetString("CMS_ERROR_513", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status salah.
        /// </summary>
        internal static string CMS_ERROR_514 {
            get {
                return ResourceManager.GetString("CMS_ERROR_514", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device busy or Invalid Character in string.
        /// </summary>
        internal static string CMS_ERROR_515 {
            get {
                return ResourceManager.GetString("CMS_ERROR_515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to panjang tidak valid.
        /// </summary>
        internal static string CMS_ERROR_516 {
            get {
                return ResourceManager.GetString("CMS_ERROR_516", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karakter tidak valid dalam PDU.
        /// </summary>
        internal static string CMS_ERROR_517 {
            get {
                return ResourceManager.GetString("CMS_ERROR_517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter tidak valid.
        /// </summary>
        internal static string CMS_ERROR_518 {
            get {
                return ResourceManager.GetString("CMS_ERROR_518", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karakter atau Panjang tidak valid .
        /// </summary>
        internal static string CMS_ERROR_519 {
            get {
                return ResourceManager.GetString("CMS_ERROR_519", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karakter tidak valid dalam teks.
        /// </summary>
        internal static string CMS_ERROR_520 {
            get {
                return ResourceManager.GetString("CMS_ERROR_520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer berakhir.
        /// </summary>
        internal static string CMS_ERROR_521 {
            get {
                return ResourceManager.GetString("CMS_ERROR_521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sementara Operasi tidak diijinkan.
        /// </summary>
        internal static string CMS_ERROR_522 {
            get {
                return ResourceManager.GetString("CMS_ERROR_522", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM tidak siap.
        /// </summary>
        internal static string CMS_ERROR_532 {
            get {
                return ResourceManager.GetString("CMS_ERROR_532", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Broadcast kesalahan yang tidak diketahui.
        /// </summary>
        internal static string CMS_ERROR_534 {
            get {
                return ResourceManager.GetString("CMS_ERROR_534", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol stack busy.
        /// </summary>
        internal static string CMS_ERROR_535 {
            get {
                return ResourceManager.GetString("CMS_ERROR_535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter tidak valid.
        /// </summary>
        internal static string CMS_ERROR_538 {
            get {
                return ResourceManager.GetString("CMS_ERROR_538", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fasilitas yang diminta tidak diterapkan.
        /// </summary>
        internal static string CMS_ERROR_69 {
            get {
                return ResourceManager.GetString("CMS_ERROR_69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator ditentukan pembatasan.
        /// </summary>
        internal static string CMS_ERROR_8 {
            get {
                return ResourceManager.GetString("CMS_ERROR_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid mentransfer pesan singkat nilai referensi.
        /// </summary>
        internal static string CMS_ERROR_81 {
            get {
                return ResourceManager.GetString("CMS_ERROR_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid pesan yang tidak ditentukan.
        /// </summary>
        internal static string CMS_ERROR_95 {
            get {
                return ResourceManager.GetString("CMS_ERROR_95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid informasi wajib.
        /// </summary>
        internal static string CMS_ERROR_96 {
            get {
                return ResourceManager.GetString("CMS_ERROR_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesan non jenis ada atau tidak dilaksanakan.
        /// </summary>
        internal static string CMS_ERROR_97 {
            get {
                return ResourceManager.GetString("CMS_ERROR_97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak kompatibel dengan protokol pesan singkat pesan.
        /// </summary>
        internal static string CMS_ERROR_98 {
            get {
                return ResourceManager.GetString("CMS_ERROR_98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informasi elemen non-ada atau tidak implemen.
        /// </summary>
        internal static string CMS_ERROR_99 {
            get {
                return ResourceManager.GetString("CMS_ERROR_99", resourceCulture);
            }
        }
    }
}
